spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      # FOR 1000m Core and 1Gi Memory
      maximum-pool-size: 35
server:
  tomcat:
    threads:
      # FOR 1000m Core and 1Gi Memory
      max: 60

websiteUrl: ${WEBSITE_URL}
frontend:
  urls: ${FRONTEND_URLS}
orderCancelPath: ${ORDER_CANCEL_PATH}
orderSuccessPath: ${ORDER_SUCCESS_PATH}