spring.application.name=spring-store-app
application.payment-gateway=PAYPAL
server.port=8000
spring.datasource.url=jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=basmalah