server:
  port: ${PORT:8000}
spring:
  application:
    name: spring-store-app
  jwt:
    secret: ${APP_JWT_SECRET_KEY:dummy_jwt_secret_key}
    accessTokenExpiration: 7200
    refreshTokenExpiration: 604800
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY:dummy_stripe_secret_key}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY:dummy_webhook_secret_key}
