spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      # FOR 1000m Core and 1Gi Memory
      maximum-pool-size: 35
      minimum-idle: 10
  data:
    redis:
      host: ${REDIS_SERVICE_HOSTNAME}
      port: ${REDIS_SERVICE_PORT}
  cache:
    type: redis
  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: false
    time-zone: Asia/Jakarta

server:
  tomcat:
    threads:
      # FOR 1000m Core and 1Gi Memory
      max: 100

websiteUrl: ${WEBSITE_URL}
frontend:
  urls: ${FRONTEND_URLS}
orderCancelPath: ${ORDER_CANCEL_PATH}
orderSuccessPath: ${ORDER_SUCCESS_PATH}