spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  cache:
    type: redis
    redis:
      time-to-live: 600s
      cache-null-values: false
  jpa:
    show-sql: true

websiteUrl: http://localhost:5173
frontend:
  urls: http://localhost:5173,http://localhost:4173
orderCancelPath: /order-cancel
orderSuccessPath: /order-success

management:
  health:
    redis:
      enabled: false